jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
#  token-validity-in-seconds: 3600 # ttl (초)
file:
  upload-dir: C:\MnJ\Fitties\vue-fitties\src\assets